config/routes.rb
DirectorioApp::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/help"

  resources :dependencies

  resources :phones

  resources :depedencies
  root :to => 'phones#index'

end

app/models/depedency.rb
class Depedency < ActiveRecord::Base
  has_many :phone
  attr_accessible :name
end

app/models/dependency.rb
class Dependency < ActiveRecord::Base
  attr_accessible :name
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :dependency
  attr_accessible :comments, :dependency_id, :name, :numbers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/depedencies_controller.rb
class DepedenciesController < ApplicationController
  # GET /depedencies
  # GET /depedencies.json
  def index
    @depedencies = Depedency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @depedencies }
    end
  end

  # GET /depedencies/1
  # GET /depedencies/1.json
  def show
    @depedency = Depedency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @depedency }
    end
  end

  # GET /depedencies/new
  # GET /depedencies/new.json
  def new
    @depedency = Depedency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @depedency }
    end
  end

  # GET /depedencies/1/edit
  def edit
    @depedency = Depedency.find(params[:id])
  end

  # POST /depedencies
  # POST /depedencies.json
  def create
    @depedency = Depedency.new(params[:depedency])

    respond_to do |format|
      if @depedency.save
        format.html { redirect_to @depedency, notice: 'Depedency was successfully created.' }
        format.json { render json: @depedency, status: :created, location: @depedency }
      else
        format.html { render action: "new" }
        format.json { render json: @depedency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /depedencies/1
  # PUT /depedencies/1.json
  def update
    @depedency = Depedency.find(params[:id])

    respond_to do |format|
      if @depedency.update_attributes(params[:depedency])
        format.html { redirect_to @depedency, notice: 'Depedency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @depedency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depedencies/1
  # DELETE /depedencies/1.json
  def destroy
    @depedency = Depedency.find(params[:id])
    @depedency.destroy

    respond_to do |format|
      format.html { redirect_to depedencies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  # GET /dependencies
  # GET /dependencies.json
  def index
    @dependencies = Dependency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dependencies }
    end
  end

  # GET /dependencies/1
  # GET /dependencies/1.json
  def show
    @dependency = Dependency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dependency }
    end
  end

  # GET /dependencies/new
  # GET /dependencies/new.json
  def new
    @dependency = Dependency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dependency }
    end
  end

  # GET /dependencies/1/edit
  def edit
    @dependency = Dependency.find(params[:id])
  end

  # POST /dependencies
  # POST /dependencies.json
  def create
    @dependency = Dependency.new(params[:dependency])

    respond_to do |format|
      if @dependency.save
        format.html { redirect_to @dependency, notice: 'Dependency was successfully created.' }
        format.json { render json: @dependency, status: :created, location: @dependency }
      else
        format.html { render action: "new" }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dependencies/1
  # PUT /dependencies/1.json
  def update
    @dependency = Dependency.find(params[:id])

    respond_to do |format|
      if @dependency.update_attributes(params[:dependency])
        format.html { redirect_to @dependency, notice: 'Dependency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependencies/1
  # DELETE /dependencies/1.json
  def destroy
    @dependency = Dependency.find(params[:id])
    @dependency.destroy

    respond_to do |format|
      format.html { redirect_to dependencies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phones }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @phone = Phone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/new
  # GET /phones/new.json
  def new
    @phone = Phone.new
    @dependencies= Dependency.all.map{|dependency|[dependency.name,dependency.id]}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/1/edit
  def edit
    @phone = Phone.find(params[:id])
    @dependencies= Dependency.all.map{|dependency|[dependency.name,dependency.id]}
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(params[:phone])

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render json: @phone, status: :created, location: @phone }
      else
        format.html { render action: "new" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phones/1
  # PUT /phones/1.json
  def update
    @phone = Phone.find(params[:id])

    respond_to do |format|
      if @phone.update_attributes(params[:phone])
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depedencies_helper.rb
module DepedenciesHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/depedencies/_form.html.erb
<%= form_for(@depedency) do |f| %>
  <% if @depedency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@depedency.errors.count, "error") %> prohibited this depedency from being saved:</h2>

      <ul>
      <% @depedency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depedencies/edit.html.erb
<h1>Editing depedency</h1>

<%= render 'form' %>

<%= link_to 'Show', @depedency %> |
<%= link_to 'Back', depedencies_path %>

app/views/depedencies/index.html.erb
<h1>Listing depedencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @depedencies.each do |depedency| %>
  <tr>
    <td><%= depedency.name %></td>
    <td><%= link_to 'Show', depedency %></td>
    <td><%= link_to 'Edit', edit_depedency_path(depedency) %></td>
    <td><%= link_to 'Destroy', depedency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Depedency', new_depedency_path %>

app/views/depedencies/new.html.erb
<h1>New depedency</h1>

<%= render 'form' %>

<%= link_to 'Back', depedencies_path %>

app/views/depedencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @depedency.name %>
</p>


<%= link_to 'Edit', edit_depedency_path(@depedency) %> |
<%= link_to 'Back', depedencies_path %>

app/views/dependencies/_form.html.erb
<%= form_for(@dependency) do |f| %>
  <% if @dependency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dependency.errors.count, "error") %> no permitieron que se grabara la dependencia></h2>

      <ul>
      <% @dependency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,'Dependencia' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar',:class=>'btn  btn-info' %>
  </div>
<% end %>

app/views/dependencies/edit.html.erb
<h1>Modificar dependencia</h1>

<%= render 'form' %>


<%= link_to 'Mostrar', @dependency, :class=>'btn btn-mini '%>
<%= link_to 'Regresar', dependencies_path, :class=>'btn btn-mini '%>

app/views/dependencies/index.html.erb
<div class="box gradient">
<div class="title">
	<h4>
	<span>Dependencias</span>
	</h4>
</div>
<div class="content noPad clearfix">
  <table  cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
  <thead>
  <tr>
     <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
   <tbody>
<% @dependencies.each do |dependency| %>
  <tr>
    <td><%= dependency.name %></td>
    <td>  <i class='icon-eye-open'></i> <%= link_to " Detalle", dependency %></td>
    <td><i class="icon-pencil"> </i> <%= link_to 'Modificar', edit_dependency_path(dependency) %></td>
    <td><i class="icon-trash"> </i>  <%= link_to 'Borrar', dependency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
<tfoot>
	<tr>
	<th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
	</tr>
</tfoot>
</table>

</div>
</div>

<%= link_to 'Agregar dependencia', new_dependency_path,:class=>'btn btn-info' %>

app/views/dependencies/new.html.erb
<h1 class="text-info">Agregar dependencia</h1>

<%= render 'form' %>

<%= link_to 'Regresar', dependencies_path, :class=>'btn btn-mini '%>

app/views/dependencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dependency.name %>
</p>



<%= link_to 'Modificar', edit_dependency_path(@dependency), :class=>'btn btn-mini '%>
<%= link_to 'Regresar', dependencies_path, :class=>'btn btn-mini '%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directorio Corral</title>
  <%= stylesheet_link_tag    "application",  :cache => false  %>
   <%= stylesheet_link_tag    "bootstrap/bootstrap-responsive.min" %>
   <%= stylesheet_link_tag    "bootstrap/bootstrap.min" %>
    <%= stylesheet_link_tag    "main" %>
      <%= stylesheet_link_tag    "icons" %>
     <%= stylesheet_link_tag    "scaffolds" %>

   <%= stylesheet_link_tag    "supr-theme/jquery.ui.core" %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.datepicker" %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.dialog." %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.progressbar" %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.resizable." %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.slider" %>
    <%= stylesheet_link_tag    "supr-theme/jquery.ui.slider." %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.stepper" %>
    <%= stylesheet_link_tag    "supr-theme/jquery.ui.supr." %>
   <%= stylesheet_link_tag    "supr-theme/jquery.ui.theme" %>
 <%= stylesheet_link_tag  "plugins/dataTables/jquery.dataTables"%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="qLoverlay"></div>
<div id="qLbar"></div>
	<div id="header">

        <div class="navbar">
            <div class="navbar-inner">
              <div class="container-fluid">
                <a href="dashboard.html" class="brand">Directorio<span class="slogan">Corral</span></a>
                <div class="nav-no-collapse">
                   
                  
                    <ul class="nav pull-right usernav">
                       <!--  <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="icon16 icomoon-icon-bell"></span><span class="notification">3</span>
                            </a>
                             <ul class="dropdown-menu">
                                <li class="menu">
                                 <ul class="notif">
                                        <li class="header"><strong>Notifications</strong> (3) items</li>
                                        <li>
                                            <a href="#">
                                                <span class="icon"><span class="icon16 icomoon-icon-user-2"></span></span>
                                                <span class="event">1 User is registred</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="icon"><span class="icon16 icomoon-icon-comments-4"></span></span>
                                                <span class="event">Jony add 1 comment</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="icon"><span class="icon16 icomoon-icon-new"></span></span>
                                                <span class="event">admin Julia added post with a long description</span>
                                            </a>
                                        </li>
                                        <li class="view-all"><a href="#">View all notifications <span class="icon16  icomoon-icon-arrow-right-7"></span></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>-->
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle avatar" href="#">
                                <img class="image" alt="" src="/assets/avatar.jpg"> 
                                <span class="txt">admin@supr.com</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="menu">
                                    <ul>
                                        <li>
                                            <a href="#"><span class="icon16 icomoon-icon-user-3"></span>Edit profile</a>
                                        </li>
                                        <li>
                                            <a href="#"><span class="icon16 icomoon-icon-comments-2"></span>Approve comments</a>
                                        </li>
                                        <li>
                                            <a href="#"><span class="icon16 entypo-icon-contact"></span>Add user</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="index.html"><span class="icon16 icomoon-icon-exit"></span> Logout</a></li>
                    </ul>
                </div><!-- /.nav-collapse -->
              </div>
            </div><!-- /navbar-inner -->
          </div><!-- /navbar --> 

    </div>
    <div id="wrapper">
    	<div class="resBtn">
            <a href="#" class=""><span class="icon16 minia-icon-list-3"></span></a>
        </div>
        <div class="collapseBtn">
             <a class="tipR" href="#" oldtitle="Hide sidebar" title=""><span class="icon12 minia-icon-layout"></span></a>
        </div>
        <div id="sidebarbg"></div>
        <div id="sidebar">

            <div class="shortcuts" style="">
                <ul>
                    <li><a class="tip pull-left" href="/static_pages/about" oldtitle="Support section" title="" aria-describedby="ui-tooltip-0"><span class="icon24 wpzoom-support"></span></a></li>
                    <!--<li><a class="tip" href="#" oldtitle="Database backup" title=""><span class="icon24 icomoon-icon-database"></span></a></li>
                    <li><a class="tip" href="#" oldtitle="Sales statistics" title=""><span class="icon24 iconic-icon-chart"></span></a></li>
                    <li><a class="tip" href="#" oldtitle="Write post" title="" aria-describedby="ui-tooltip-3"><span class="icon24 icomoon-icon-pencil"></span></a></li>
                -->
                </ul>
            </div><!-- End search -->            

            <div class="sidenav" style="">

                <div style="margin: 2px 0 0 0;" class="sidebar-widget">
                    <h5 style="margin-bottom:0" class="title">Navigation</h5>
                </div><!-- End .sidenav-widget -->

                <div class="mainnav">
                    <ul>
                    	 <li>
                            <a href="#" class="hasUl"><i class="icon16 icon-tag"></i>Telefonos<span class="hasDrop icon16 icomoon-icon-arrow-down"></span></a>
                            <ul class="sub">
                                <li><a href="/phones"><span class="icon16 icomoon-icon-paper"></span>Listado</a></li>
                                <li><a href="/phones/new"><span class="icon16 icomoon-icon-paper"></span>Agregar</a></li>
                            </ul>
                            </li>
                        <!--<li>greg
                            <a href="#" class="hasUl"><span class="icon16 minia-icon-list-4"></span>Forms<span class="hasDrop icon16 icomoon-icon-arrow-down"></span></a>
                            <ul class="sub">
                                <li><a href="forms.html"><span class="icon16 icomoon-icon-paper"></span>Forms Stuff</a></li>
                                <li><a href="forms-validation.html"><span class="icon16 icomoon-icon-paper"></span>Validation</a></li>
                            </ul>
                        </li>-->
                       
                       
                        <li><a href="#"> <i class="icon-folder-close"></i> Dependencias</a><ul class="sub">
                                <li><a href="/dependencies"><span class="icon16 icomoon-icon-paper"></span>Listado</a></li>
                                <li><a href="/dependencies/new"><span class="icon16 icomoon-icon-paper"></span>Agregar</a></li>
                            </ul>
                            </li>
                    </ul>
                </div>
            </div><!-- End sidenav -->

         
        </div>
    </div>
	<div id="mainBody">
	 	<div id="content" class="clearfix">
		<div class="contentwrapper">
		<div class="heading">
                    <h3>Dashboard</h3>                    

                    <div class="resBtnSearch">
                        <a href="#"><spabznHJZGXhXvbHXbzBXvx vn class="icon16 brocco-icon-search"></span></a>
                    </div>

                    <div class="search">

                        <form action="search.html" id="searchform">
                            <input type="text" placeholder="Search here ..." class="top-search text" id="tipue_search_input">
                            <input type="submit" value="" class="search-btn nostyle" id="tipue_search_button">
                        </form>
                
                    </div><!-- End search -->
                    
                    <ul class="breadcrumb">
                        <li>You are here:</li>
                        <li>
                            <a class="tip" href="#" oldtitle="back to dashboard" title="">
                                <span class="icon16 icomoon-icon-screen"></span>
                            </a> 
                            <span class="divider">
                                <span class="icon16 icomoon-icon-arrow-right"></span>
                            </span>
                        </li>
                        <li class="active">Dashboard</li>
                    </ul>

                </div>
            <div class="row-fluid">

                        <div class="span12">
              <%= yield %>
              </div>
              </div>
		</div>
		</div>

		
		</div>
	

</body>
</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript" ></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js" type="text/javascript"></script>
<%=javascript_include_tag "bootstrap","plugins/dataTables/jquery.dataTables.min","plugins/sparkline/jquery.sparkline.min","plugins/responsive-tables/responsive-tables","plugins/animated-progress-bar/jquery.progressbar","rails","plugins/knob/jquery.knob","zmain"%>
<script>
$(document).ready(function() {
				$('#tabla').dataTable( {
					"sDom": "<'row'<'span8'l><'span8'f>r>t<'row'<'span8'i><'span8'p>>",
					"sPaginationType": "bootstrap",
					"oLanguage": {
						"sLengthMenu": "_MENU_ records per page"
					}
				} );
			} );
</script>

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :numbers,'Telefonos' %><br />
    <%= f.text_field :numbers %>
  </div>
  <div class="field">
    <%= f.label :dependency_id ,'Dependencia'%><br />
     	<%= f.select   :dependency_id,@dependencies %>
   
  </div>
  <div class="field">
    <%= f.label :comments,'Comentarios' %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
      <%= f.submit 'Guardar',:class=>'btn  btn-info' %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>


<%= link_to 'Mostrar', @phone, :class=>'btn btn-mini '%>
<%= link_to 'Regresar', phones_path, :class=>'btn btn-mini '%>

app/views/phones/index.html.erb
<div class="box gradient">
<div class="title">
	<h4>
	<span>Telefonos</span>
	</h4>
</div>
<div class="content noPad clearfix">
  <table  cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered" width="100%">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Numero</th>
    <th>Dependencia</th>
    <th>Comentarios</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
   <tbody>
<% @phones.each do |phone| %>
  <tr>
    <td><%= phone.name %></td>
    <td><%= phone.numbers %></td>
    <td><%= phone.dependency.name %></td>
    <td><%= phone.comments %></td>
    <td><i class='icon-eye-open'></i>  <%= link_to 'Show', phone %></td>
    <td><i class="icon-pencil"> </i><%= link_to 'Edit', edit_phone_path(phone) %></td>
    <td><i class="icon-trash"> </i><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
<tfoot>
<tr>
                                                <th>Nombre</th>
                                                <th>Numero</th>
                                                <th>Dependencia</th>
                                                <th>Comentarios</th>
                                                <th></th>
                                                <th></th>
                                                 <th></th>
                                            </tr>
                                        </tfoot>
</table>

</div>
</div>
<%= link_to 'Agregar telefono ',  new_phone_path,:class=>'btn btn-info' %>

app/views/phones/new.html.erb
<h1>Agregar telefono</h1>

<%= render 'form' %>

<%= link_to 'Regresar', dependencies_path, :class=>'btn btn-mini '%>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @phone.name %>
</p>

<p>
  <b>Número:</b>
  <%= @phone.numbers %>
</p>

<p>
  <b>Dependencia</b>
  <%= @phone.dependency.name %>
</p>

<p>
  <b>Comentarios</b>
  <%= @phone.comments %>
</p>

<%= link_to 'Modificar',  edit_phone_path(@phone), :class=>'btn btn-mini '%>
<%= link_to 'Regresar',  phones_path , :class=>'btn btn-mini '%>

app/views/static_pages/about.html.erb
<h1>Directorio Corral</h1>
   Desarrollado por:
     
    <address>
    <strong>Ing. David Israel Raygoza Ramirez</strong><br>
    <strong>Linkedin: </strong> <a href="http://lnkd.in/z9XAvq">http://lnkd.in/z9XAvq </a><br />
     <strong>Email </strong><a href="mailto:david.raygoza.ramirez@gmail.com">david.raygoza.ramirez@gmail.com</a>
    </address>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>